oldify:
	convert pl-logo.png -dither FloydSteinberg -colors 4 pline.gif
	convert pline.gif -fill '#0033FF' -opaque '#12B0ED' pline.gif
	convert pline.gif -fill '#66CC00' -opaque '#A5D638' pline.gif
	convert pline.gif -fill '#99CCCC' -opaque '#B0CAD1' pline.gif
	convert pline.gif -transparent '#FDFEFE' pline.gif

	convert baydin.jpg -resize 160x160 -dither FloydSteinberg -colors 2 baydin.gif
	convert baydin.gif -fill '#000000' -opaque '#5E5E5E' baydin.gif

	convert cordray.jpg -resize 160x160 -dither FloydSteinberg -colors 8 cordray.gif

	convert levine.png -resize 160x160 -dither FloydSteinberg -colors 8 levine.gif